E_NB = {'stops': ['Lincoln', 'County Line', 'Dry Creek', 'Arapahoe at Village Center',
                  'Orchard', 'Belleview', 'Southmoor', 'Yale', 'Colorado', 'UDenver',
                  'Louisiana - Pearl', 'I-25 & Broadway', 'Alameda', '10th & Osage',
                  'Auraria West', 'Sports Authority Field', 'Pepsi Center', 'Union Station'],
        'Lincoln': [],
        'County Line': [],
        'Dry Creek': ['343PM', '358PM', '413PM', '428PM', '443PM', '458PM', '513PM'],
        'Arapahoe at Village Center': [],
        'Orchard': [],
        'Belleview': [],
        'Southmoor': [],
        'Yale': [],
        'Colorado': [],
        'UDenver': [],
        'Louisiana - Pearl': [],
        'I-25 & Broadway': [],
        'Alameda': [],
        '10th & Osage': [],
        'Auraria West': [],
        'Sports Authority Field': [],
        'Pepsi Center': [],
        'Union Station': []}

E_SB = {'stops': ['Union Station', 'Pepsi Center', 'Sports Authority Field', 'Auraria West',
                  '10th & Osage', 'Alameda', 'I-25 & Broadway', 'Louisiana - Pearl',
                  'UDenver', 'Colorado', 'Yale', 'Southmoor', 'Belleview', 'Orchard',
                  'Arapahoe at Village Center', 'Dry Creek', 'County Line', 'Lincoln'],
        'Lincoln': [],
        'County Line': [],
        'Dry Creek': [],
        'Arapahoe at Village Center': [],
        'Orchard': [],
        'Belleview': [],
        'Southmoor': [],
        'Yale': [],
        'Colorado': [],
        'UDenver': ['701AM', '716AM', '731AM', '746AM', '801AM', '816AM', '831AM'],
        'Louisiana - Pearl': [],
        'I-25 & Broadway': [],
        'Alameda': [],
        '10th & Osage': [],
        'Auraria West': [],
        'Sports Authority Field': [],
        'Pepsi Center': [],
        'Union Station': []}

trains = {'E' : {1: E_NB, 0: E_SB}}