E = {'stops': ['Lincoln', 'County Line', 'Dry Creek', 'Arapahoe', 'Orchard', 'Belleview',
               'Southmoor', 'Yale', 'Colorado', 'UDenver', 'Louisiana - Pearl',
               'I-25 & Broadway', 'Alameda', '10th & Osage', 'Auraria West',
               'Sports Authority Field', 'Pepsi Center', 'Union Station'],
     'Lincoln': {'NB': [],
                 'SB': []},
     'County Line': {'NB': [],
                     'SB': []},
     'Dry Creek': {'NB': ['343PM', '358PM', '413PM', '428PM', '443PM', '458PM', '513PM'],
                   'SB': []},
     'Arapahoe': {'NB': [],
                  'SB': []},
     'Orchard': {'NB': [],
                 'SB': []},
     'Belleview': {'NB': [],
                   'SB': []},
     'Southmoor': {'NB': [],
                   'SB': []},
     'Yale': {'NB': [],
              'SB': []},
     'Colorado': {'NB': [],
                  'SB': []},
     'UDenver': {'NB': [],
                 'SB': ['701AM', '716AM', '731AM', '746AM', '801AM', '816AM', '831AM']},
     'Louisiana-Pearl': {'NB': [],
                           'SB': []},
     'I-25 & Broadway': {'NB': [],
                         'SB': []},
     'Alameda': {'NB': [],
                 'SB': []},
     '10th & Osage': {'NB': [],
                      'SB': []},
     'Auraria West': {'NB': [],
                      'SB': []},
     'Sports Authority Field': {'NB': [],
                                'SB': []},
     'Pepsi Center': {'NB': [],
                      'SB': []},
     'Union Station': {'NB': [],
                       'SB': []}
     }

DC_STATIONS = {
    'Van Ness-UDC': {},
    'Fort Totten': {},
    'Brookland-CUA': {},
    'Shady Grove': {},
    'Dupont Circle': {},
    'Takoma': {},
    'Bethesda': {},
    'Silver Spring': {},
    'Union Station': {},
    'Cleveland Park': {},
    'Medical Center': {},
    'Judiciary Square': {},
    'Rockville': 'A14',
    'NoMa-Gallaudet U': {},
    'Glenmont': {},
    'Twinbrook': {},
    'Metro Center': 'A01',
    'Gallery Place': {},
    'Rhode Island Avenue-Brentwood': {},
    'White Flint': {},
    'Grosvenor-Strathmore': {},
    'Friendship Heights': {},
    'Tenleytown-AU': {},
    'Forest Glen': {},
    'Farragut North': {},
    'Woodley Park': {},
    'Wheaton': {}
}
DC_TRAINS = {
    'red': 'RD'
}
# TODO: strptime all the strings in E train for Denver

DC_LIVE_TRAIN_URL = 'https://www.wmata.com/js/nexttrain/nexttrain.html#'

TRAINS = {'Denver': {'E': E}}