# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 15:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message=b'Phone number must be entered in the form +9999999999', regex=b'^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
